project:
  type: website
  output-dir: docs

website:
  title: "Juan Hernández Guizar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Resume.qmd
        text: Resume

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



