project:
  type: website
  output-dir: docs

website:
  title: "Juan Hernández Guizar"
  navbar:
    left:
      - href: index.qmd
        text: '<i class="bi bi-house"></i> Home'
      - href: Resume.qmd
        text: '<i class="bi bi-newspaper"></i> Resume'

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    includes:
      in-header: bootstrap-icons.html